package main

const (
	ok                           string = "OK"
	strFirstStart                string = "This is the first start\n"
	strCreateWorkDirs            string = "* Creating work directory\n"
	strCreateStorage             string = "* Creating storage\n"
	strUpdatingGoCache           string = "Updating Golang cache...\t"
	strUpdatingLiteIDECache      string = "Updating LiteIDE cache...\t"
	strInstalledVersions         string = "* Installed %s versions\n"
	strArchivesListing           string = "Archives listing"
	strFetchRemote               string = "Fetch remote version's list"
	strPleaseSetTool             string = "Please, set 'go' or 'liteide'"
	strDownloading               string = "Downloading version: %s\n"
	strDownloadingGo             string = "Downloading Go version: %s\n"
	strDownloadingLiteIDE        string = "Dowloading LiteIDE version %s\n"
	strDownloadingLiteIDEversion string = "Dowloading LiteIDE version %s %s\n"
	strDownloadingInstalling     string = "Downloading and installing version: %s\n"
	strInstallGoVersion          string = "Install Golang version %s\n"
	strUninstallGo               string = "Uninstall Golang version"
	strUninstallLiteIDE          string = "Uninstall Liteide version"
	strChecksumMismatch          string = "Checksum mismatch"
	strOperationAborted          string = "Operation aborted"
	strAlreadyDownloaded         string = "Already downloaded..."
	strFilesMismatch             string = "Files mismatch"
	strFileRemoved               string = "File removed"
)
